import { Navigation } from "@/components/navigation/Navigation";
import { TailwindIndicator } from "@/components/theme/TailwindIndicator";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { SanityLive } from "@/sanity/lib/live";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth h-screen`}
      >
        <ThemeProvider
          attribute="class"
          forcedTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <section className="min-h-screen w-auto">
            <div className="w-full flex flex-col md:flex-row h-screen">
              <Navigation />
              <main className="py-12 px-6 md:p-6 xl:p-12 mx-auto w-full h-full">
                {children}
              </main>
            </div>
          </section>
        </ThemeProvider>
        <SanityLive />
        <TailwindIndicator />
      </body>
    </html>
  );
}
